# Automatically build the project and run any configured tests for every push
# and submitted pull request. This helps catch platform-specific issues and 
# provides a defense against bad commits.

name: Build Mod

on:
  push:
    branches:
      - main  # Trigger build on pushes to main branch
  pull_request:
    branches:
      - main  # Trigger build on PRs to main branch

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [21]  # Current Java LTS; add more versions here if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set Up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew build

      - name: Capture Build Artifacts
        if: ${{ matrix.java == '21' }}  # Upload artifacts only for Java 21 build
        uses: actions/upload-artifact@v4
        with:
          name: mod-build  # Custom artifact name for clarity
          path: build/libs/*.jar  # Path to the mod's JAR file(s)
